### ISSUE TITLE
Error installing via ZPM

### ISSUE THREAD

**Issue by SergeyMi37** [intersystems-community/objectscript-package-template#1]
zpm "install objectscript-package-template"
[objectscript-package-template] Reload START (D:\InterSystems\IRISDEV\mgr\.modules\OBJECTSCRIPTPACKAGETEMPLATE\objectscript-package-template\1.0.3\)
[objectscript-package-template] Reload FAILURE
ERROR! Файл 'D:\InterSystems\IRISDEV\mgr\.modules\OBJECTSCRIPTPACKAGETEMPLATE\objectscript-package-template\1.0.3\src\gbl\community.objectscript.settings.xml' не существует
ОШИБКА #5012: Файл 'D:\InterSystems\IRISDEV\mgr\.modules\OBJECTSCRIPTPACKAGETEMPLATE\objectscript-package-template\1.0.3\src\gbl\community.objectscript.settings.xml' не существует

**Comment by rcemper** [comment]
works in docker without problems

**Comment by SergeyMi37** [comment]
Yes it works
